

models_list:
  - model_name: anthropic/claude-opus-4-5-20251101
    engine: anthropic/claude-opus-4-5-20251101

  - model_name: anthropic/claude-haiku-4-5-20251001
    engine: anthropic/claude-haiku-4-5-20251001

  - model_name: anthropic/claude-sonnet-4-5-20250929
    engine: anthropic/claude-sonnet-4-5-20250929

  - model_name: google-vertex/gemini-3-pro-preview
    engine: google-vertex/gemini-3-pro-preview

  - model_name: google-vertex/gemini-2.5-flash
    engine: google-vertex/gemini-2.5-flash
    
  - model_name: google-vertex/gemini-2.5-pro
    engine: google-vertex/gemini-2.5-pro
