

models_list:
  - model_name: deepseek-ai/deepseek-v3-1-250821
    engine: "deepseek-v3-1-250821"

  - model_name: deepseek-ai/deepseek-r1-250528
    engine: "deepseek-r1-250528"

  - 

  - model_name: scienceone/s1-base-ultra
    engine: "S1-Base-Ultra"
